DEFAULT_CATEGORIES = [
  { name: "Fruits"},
  { name: "Vegetables"},
  { name: "Meats"},
  { name: "Medicals"},
  { name: 'Groceries' },
  { name: 'Clothing' },
  { name: 'Electronics' },
  { name: 'Home Decor' },
  { name: 'Toys' },
  { name: 'Beauty' },
  { name: 'Sport Wears' },
  { name: 'Office Supplies' },
  { name: 'Books' },
  { name: 'Pet Supplies' },
  { name: 'Tools' },
  { name: 'Automotive' },
  { name: 'Baby' },
  { name: 'Music' },
  { name: 'Movies' },
  { name: 'Jewelry' },
  { name: 'Shoes' },
  { name: 'Accessories' },
  { name: 'Food' },
  { name: 'Kitchen' },
  { name: 'Health' },
  { name: 'Outdoor' },
  { name: 'Travel' },
  { name: 'School Supplies' },
  { name: 'Art Supplies' },
  { name: 'Crafts' },
  { name: 'Garden' },
  { name: 'Party Supplies' },
  { name: 'Fitness' }
]